### ISSUE TITLE
Move install script from a Gist to the repo

### ISSUE THREAD

**Issue by calebkleveter** [calebkleveter/Ether#5]
The install script which is located [here](https://gist.github.com/calebkleveter/2e5490c76df227c510035515a49f9f01) should be moved to the repo's root in a file named `install.sh`. This will make the install command quite a bit shorter because you can then access the script at the URL `https://raw.githubusercontent.com/calebkleveter/Ether/master/install.sh`

**Comment by ashwani99** [comment]
Can I take this?

**Comment by calebkleveter** [comment]
Definitely!

**Comment by AmadeusDelfino** [comment]
I'm already doing! = D

**Comment by calebkleveter** [comment]
*Let the race begin*

**Comment by ashwani99** [comment]
@calebkleveter Please check

**Comment by calebkleveter** [comment]
Thanks! I accepted both of them.
